export interface Student {
  id: string;
  student_id: string;
  admission_number: string;
  admission_date: string;
  first_name: string;
  last_name: string;
  middle_name?: string;
  other_names?: string;
  gender: 'male' | 'female' | 'other';
  passport_url?: string;
  date_of_birth: string;
  place_of_birth?: string;
  nationality: string;
  state_of_origin?: string;
  lga?: string;
  religion?: string;
  blood_group?: string;
  genotype?: string;
  phone_number?: string;
  email?: string;
  home_address: string;
  residential_address?: string;
  branch_id: string;
  department?: string;
  class_id?: string;
  class_arm?: string;
  house_id?: string;
  club_id?: string;
  transportation_status: boolean;
  pickup_location?: string;
  bus_route_id?: string;
  medical_info: any;
  doctor_name?: string;
  hospital_name?: string;
  allergies?: string;
  medical_conditions?: string;
  special_needs?: string;
  previous_school?: string;
  transfer_status: boolean;
  admission_status: 'pending' | 'admitted' | 'rejected' | 'waitlisted';
  current_status: 'active' | 'inactive' | 'graduated' | 'transferred' | 'suspended' | 'expelled';
  emergency_contact: any;
  parent_id?: string;
  guardian_info: any;
  documents: any[];
  qr_code_data?: string;
  barcode_data?: string;
  created_by?: string;
  created_at: string;
  updated_at: string;
  metadata: any;
}

export interface StudentRegistrationData {
  first_name: string;
  last_name: string;
  middle_name?: string;
  other_names?: string;
  gender: 'male' | 'female' | 'other';
  date_of_birth: string;
  place_of_birth?: string;
  nationality: string;
  state_of_origin?: string;
  lga?: string;
  religion?: string;
  blood_group?: string;
  genotype?: string;
  phone_number?: string;
  email?: string;
  home_address: string;
  residential_address?: string;
  branch_id: string;
  department?: string;
  class_id?: string;
  class_arm?: string;
  house_id?: string;
  club_id?: string;
  transportation_status: boolean;
  pickup_location?: string;
  bus_route_id?: string;
  medical_info: any;
  doctor_name?: string;
  hospital_name?: string;
  allergies?: string;
  medical_conditions?: string;
  special_needs?: string;
  previous_school?: string;
  transfer_status: boolean;
  emergency_contact: any;
  guardian_info: any;
  parent_id?: string;
}
