import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, Lock, Plus, Save, Search, Send, Sparkles, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { supabase } from '../../config/supabase/client';
import { useAuth } from '../../hooks/useAuth';

type Batch = { id:string; title:string; assessment_type:string; max_score:number; status:string; assessment_date:string|null; class_id:string; subject_id:string; class_name?:string; subject_name?:string; };
type Student = { id:string; first_name:string; last_name:string; admission_number:string|null };
const roles = ['super_admin','branch_admin','director','principal','admin','record_keeper','teacher'];
const grade = (p:number) => p>=75?'A':p>=65?'B':p>=55?'C':p>=45?'D':p>=40?'E':'F';

export default function ResultsHub(){
 const {user}=useAuth(); const branchId=user?.branch_id||null;
 const [batches,setBatches]=useState<Batch[]>([]); const [classes,setClasses]=useState<any[]>([]); const [subjects,setSubjects]=useState<any[]>([]); const [students,setStudents]=useState<Student[]>([]);
 const [entries,setEntries]=useState<Record<string,string>>({}); const [selected,setSelected]=useState<Batch|null>(null); const [filter,setFilter]=useState('');
 const [form,setForm]=useState({title:'',assessment_type:'test',class_id:'',subject_id:'',max_score:'100',weight:'100',assessment_date:new Date().toISOString().slice(0,10)});
 const canEdit=roles.includes(String(user?.role));
 const load=async()=>{ if(!branchId)return; const [{data:b},{data:c},{data:s}]=await Promise.all([
  supabase.from('result_batches').select('id,title,assessment_type,max_score,status,assessment_date,class_id,subject_id,classes(name),subjects(name)').eq('branch_id',branchId).order('created_at',{ascending:false}),
  supabase.from('classes').select('id,name').eq('branch_id',branchId).eq('status','active').order('name'),
  supabase.from('subjects').select('id,name').eq('branch_id',branchId).order('name')]);
 setBatches((b||[]).map((x:any)=>({...x,class_name:x.classes?.name,subject_name:x.subjects?.name}))); setClasses(c||[]); setSubjects(s||[]);
 };
 useEffect(()=>{load()},[branchId]);
 const openBatch=async(b:Batch)=>{setSelected(b); const {data}=await supabase.from('result_entries').select('student_id,score').eq('batch_id',b.id); const map:Record<string,string>={}; (data||[]).forEach((x:any)=>map[x.student_id]=String(x.score)); setEntries(map); const {data:st}=await supabase.from('students').select('id,first_name,last_name,admission_number').eq('branch_id',branchId).eq('class_id',b.class_id).eq('current_status','active').order('last_name'); setStudents(st||[]);};
 const createBatch=async(e:React.FormEvent)=>{e.preventDefault(); if(!branchId||!form.title||!form.class_id||!form.subject_id)return toast.error('Complete the assessment details'); const {data,error}=await supabase.from('result_batches').insert({branch_id:branchId,...form,max_score:Number(form.max_score),weight:Number(form.weight),entered_by:user?.id}).select('id,title,assessment_type,max_score,status,assessment_date,class_id,subject_id').single(); if(error)return toast.error(error.message); toast.success('Assessment created'); setForm({...form,title:''}); await load(); if(data)openBatch(data as Batch);};
 const save=async(publish=false)=>{if(!selected||!branchId)return; const rows=students.map(s=>({batch_id:selected.id,student_id:s.id,score:Number(entries[s.id]||0),grade:grade((Number(entries[s.id]||0)/Number(selected.max_score))*100),remark:Number(entries[s.id]||0)>=Number(selected.max_score)*.4?'Pass':'Needs improvement',entered_by:user?.id,updated_by:user?.id})); const {error}=await supabase.from('result_entries').upsert(rows,{onConflict:'batch_id,student_id'}); if(error)return toast.error(error.message); const patch:any={status:publish?'published':'submitted',...(publish?{published_by:user?.id,published_at:new Date().toISOString()}: {})}; const r=await supabase.from('result_batches').update(patch).eq('id',selected.id); if(r.error)return toast.error(r.error.message); await supabase.from('result_publication_audits').insert({batch_id:selected.id,action:publish?'published':'submitted',performed_by:user?.id,snapshot:{entries:rows.length}}); toast.success(publish?'Results published to students/parents':'Results saved'); await load(); setSelected({...selected,...patch});};
 const visible=batches.filter(b=>`${b.title} ${b.class_name} ${b.subject_name}`.toLowerCase().includes(filter.toLowerCase()));
 const avg=useMemo(()=>{const vals=students.map(s=>Number(entries[s.id]||0)); return vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length/Number(selected?.max_score||100)*100).toFixed(1):'0.0'},[students,entries,selected]);
 return <div className="min-h-screen bg-slate-50 p-4 md:p-8 space-y-6">
  <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="flex items-center gap-2 text-indigo-600 text-sm font-semibold"><Sparkles size={16}/> ACADEMIC PERFORMANCE</div><h1 className="text-3xl font-bold text-slate-900">Results Centre</h1><p className="text-slate-500">Create, enter, review, publish and lock assessments from one workspace.</p></div><div className="flex gap-2"><span className="px-3 py-2 rounded-xl bg-white border text-sm">{batches.length} assessments</span><span className="px-3 py-2 rounded-xl bg-white border text-sm">{batches.filter(b=>b.status==='published').length} published</span></div></div>
  {canEdit&&<form onSubmit={createBatch} className="bg-white rounded-2xl border shadow-sm p-5 grid grid-cols-1 md:grid-cols-6 gap-3"><input className="input" placeholder="Assessment title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="input" value={form.assessment_type} onChange={e=>setForm({...form,assessment_type:e.target.value})}><option>test</option><option>exam</option><option>cbt</option><option>assignment</option><option>continuous_assessment</option></select><select className="input" value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" type="number" min="1" placeholder="Max score" value={form.max_score} onChange={e=>setForm({...form,max_score:e.target.value})}/><button className="rounded-xl bg-indigo-600 text-white font-semibold px-4 py-2 flex items-center justify-center gap-2"><Plus size={18}/>Create</button></form>}
  <div className="grid lg:grid-cols-[360px_1fr] gap-6"><section className="bg-white border rounded-2xl shadow-sm overflow-hidden"><div className="p-4 border-b"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" placeholder="Search assessments..." value={filter} onChange={e=>setFilter(e.target.value)}/></div></div><div className="max-h-[650px] overflow-auto">{visible.map(b=><button key={b.id} onClick={()=>openBatch(b)} className={`w-full text-left p-4 border-b hover:bg-slate-50 ${selected?.id===b.id?'bg-indigo-50':''}`}><div className="flex justify-between gap-3"><b className="text-slate-800">{b.title}</b><span className="text-xs px-2 py-1 rounded-full bg-slate-100">{b.status}</span></div><p className="text-sm text-slate-500 mt-1">{b.class_name||'Class'} · {b.subject_name||'Subject'}</p><p className="text-xs text-slate-400 mt-2 uppercase">{b.assessment_type} · /{b.max_score}</p></button>)}{!visible.length&&<div className="p-8 text-center text-slate-400">No assessments yet.</div>}</div></section>
  <section className="bg-white border rounded-2xl shadow-sm overflow-hidden">{selected?<><div className="p-5 border-b flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.title}</h2><p className="text-sm text-slate-500">{selected.class_name} · {selected.subject_name} · Max {selected.max_score}</p></div><div className="flex items-center gap-2"><span className="px-3 py-2 rounded-xl bg-slate-100 text-sm"><Users size={15} className="inline mr-1"/>{students.length}</span><span className="px-3 py-2 rounded-xl bg-indigo-50 text-indigo-700 text-sm">Average {avg}%</span>{canEdit&&selected.status!=='locked'&&<><button onClick={()=>save(false)} className="px-3 py-2 rounded-xl border flex gap-2 items-center"><Save size={16}/>Save</button><button onClick={()=>save(true)} className="px-3 py-2 rounded-xl bg-indigo-600 text-white flex gap-2 items-center"><Send size={16}/>Publish</button></>}</div></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-3">Student</th><th className="text-left p-3">Admission No.</th><th className="text-left p-3">Score / {selected.max_score}</th><th className="text-left p-3">%</th><th className="text-left p-3">Grade</th></tr></thead><tbody>{students.map(s=>{const score=Number(entries[s.id]||0),p=score/Number(selected.max_score)*100;return <tr key={s.id} className="border-t"><td className="p-3 font-medium">{s.last_name} {s.first_name}</td><td className="p-3 text-slate-500">{s.admission_number||'—'}</td><td className="p-3"><input disabled={!canEdit||selected.status==='locked'} className="w-28 rounded-lg border px-3 py-2" type="number" min="0" max={selected.max_score} value={entries[s.id]||''} onChange={e=>setEntries({...entries,[s.id]:e.target.value})}/></td><td className="p-3">{p.toFixed(1)}%</td><td className="p-3 font-bold">{grade(p)}</td></tr>})}</tbody></table></div></>:<div className="h-[500px] flex items-center justify-center text-center text-slate-400"><div><BarChart3 size={48} className="mx-auto mb-3 opacity-40"/><h3 className="text-lg font-semibold text-slate-600">Select an assessment</h3><p>Enter scores and publish when the sheet is verified.</p></div></div>}</section></div>
  <style>{`.input{width:100%;border:1px solid #e2e8f0;border-radius:.75rem;padding:.65rem .8rem;outline:none;background:#fff}.input:focus{border-color:#6366f1;box-shadow:0 0 0 3px rgba(99,102,241,.1)}`}</style>
 </div>;
}